#!/usr/bin/env python
"""Selective risk (or its CP upper bound) vs accepted fraction.

=> plots selective-error or the calibrated selective-risk UB against accepted fraction 
as the coverage threshold varies, with one curve per method: confidence-only, 
proof-existence, coverage-only, margin-only, and full CovCal.

Each curve is generated by sweeping the relevant single-axis threshold across the
predeclared grid (read from a YAML config) and re-running the selector on the *test*
split. CovCal's curve is parameterised by holding C_typ and M at fixed values from the
calibrated thresholds while sweeping C_prf (so the curve is comparable to the
proved-coverage-only curve at the calibrated typ/margin).

Output in `<run-dir>/figures/selective_risk_vs_accepted.{png,pdf}`.

Usage:
  uv run python scripts/render_figure_selective_risk.py \
      --run-dir runs/minimal \
      --observations runs/minimal/observations.jsonl \
      --splits runs/minimal/splits.json \
      --config configs/minimal.yaml \
      --thresholds runs/minimal/thresholds.json
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Callable
from pathlib import Path

import yaml

from covcal.calibration import clopper_pearson_upper
from covcal.selectors import (
    ConfidenceOnly,
    CovCal,
    MarginOnly,
    ProvedCoverageOnly,
    Selector,
    TypedCoverageOnly,
    proof_existence_abstention,
)
from covcal.types import FormalObservation, Thresholds


def _load_observations_jsonl(path: Path) -> list[FormalObservation]:
    """Replica of `covcal.cli._load_observations` to avoid pulling typer into the script."""
    from covcal.types import ArtifactOutcome, Candidate, ClassRecord, Status
    obs_list: list[FormalObservation] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            classes = [
                ClassRecord(
                    label=c["label"],
                    weight=c["weight"],
                    candidate_indices=c.get("candidate_indices", []),
                    artifacts=[
                        ArtifactOutcome(
                            status=Status(a["status"]),
                            tactic_used=a.get("tactic_used"),
                            elapsed_seconds=a.get("elapsed_seconds", 0.0),
                            log=a.get("log", ""),
                            source=a.get("source", "template"),
                        )
                        for a in c.get("artifacts", [])
                    ],
                )
                for c in d["classes"]
            ]
            candidates = [Candidate(**c) for c in d.get("candidates", [])]
            obs_list.append(
                FormalObservation(
                    problem_id=d["problem_id"],
                    classes=classes,
                    candidates=candidates,
                    prover_budget_seconds=d.get("prover_budget_seconds", 0.0),
                    metadata=d.get("metadata", {}),
                )
            )
    return obs_list


def _split_test_ids(splits_path: Path) -> set[str]:
    manifest = json.loads(splits_path.read_text(encoding="utf-8"))
    return set(manifest["test"])


def _sweep(
    observations: list[FormalObservation],
    references: dict[str, str],
    thresholds_to_sweep: list[float],
    make_selector: Callable[[float], Selector],
) -> list[tuple[float, int, int, int, float]]:
    """Return list of (threshold, m, k, n, risk_ub_95) per threshold value."""
    rows: list[tuple[float, int, int, int, float]] = []
    n = len(observations)
    for tau in thresholds_to_sweep:
        sel = make_selector(tau)
        m, k = 0, 0
        for obs in observations:
            out = sel(obs)
            if out.abstained:
                continue
            m += 1
            ref = references.get(obs.problem_id)
            if ref is not None and out.selected != ref:
                k += 1
        ub = clopper_pearson_upper(k, m, 0.05) if m > 0 else 1.0
        rows.append((tau, m, k, n, ub))
    return rows


def _make_proof_existence(_threshold: float) -> Selector:
    # threshold is ignored; included for uniform make_selector(...) API.
    return proof_existence_abstention


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--observations", type=Path, required=True)
    parser.add_argument("--splits", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--thresholds", type=Path, required=False, default=None,
                        help="Calibrated thresholds JSON (for CovCal's anchor point).")
    args = parser.parse_args()

    # Lazy-import matplotlib so the script imports cleanly even without the viz extra.
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed; run `uv sync --extra viz` first.", flush=True)
        return 2

    observations_all = _load_observations_jsonl(args.observations)
    test_ids = _split_test_ids(args.splits)
    observations = [o for o in observations_all if o.problem_id in test_ids]
    # `obs.metadata` is typed `dict[str, object]`; coerce reference_class to str and drop
    # any None entries so `_sweep`'s `dict[str, str]` annotation is honoured.
    references: dict[str, str] = {
        o.problem_id: str(o.metadata["reference_class"])
        for o in observations
        if o.metadata.get("reference_class") is not None
    }

    cfg = yaml.safe_load(args.config.read_text(encoding="utf-8"))
    grid = cfg["calibration"]["threshold_grid"]
    sweeps: dict[str, list[tuple[float, int, int, int, float]]] = {}

    sweeps["Confidence-only"] = _sweep(
        observations, references,
        thresholds_to_sweep=[0.0, 0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
        make_selector=ConfidenceOnly,
    )
    sweeps["Proof-existence"] = _sweep(
        observations, references,
        thresholds_to_sweep=[0.0],  # a single point — no threshold
        make_selector=_make_proof_existence,
    )
    sweeps["Typed-coverage"] = _sweep(
        observations, references, grid["typ"], TypedCoverageOnly,
    )
    sweeps["Proved-coverage"] = _sweep(
        observations, references, grid["prf"], ProvedCoverageOnly,
    )
    sweeps["Margin"] = _sweep(
        observations, references, grid["margin"], MarginOnly,
    )

    # CovCal curve: sweep C_prf with C_typ and M held at the calibrated values (if any),
    # else at the median of the grid.
    if args.thresholds and args.thresholds.exists():
        cal = json.loads(args.thresholds.read_text(encoding="utf-8"))
        sel_tau = cal.get("selected") or [
            grid["typ"][len(grid["typ"]) // 2],
            grid["prf"][len(grid["prf"]) // 2],
            grid["margin"][len(grid["margin"]) // 2],
        ]
    else:
        sel_tau = [
            grid["typ"][len(grid["typ"]) // 2],
            grid["prf"][len(grid["prf"]) // 2],
            grid["margin"][len(grid["margin"]) // 2],
        ]
    fixed_typ, fixed_margin = float(sel_tau[0]), float(sel_tau[2])
    sweeps["CovCal (C_typ, M fixed; sweep C_prf)"] = _sweep(
        observations, references, grid["prf"],
        lambda p: CovCal(Thresholds(typ=fixed_typ, prf=p, margin=fixed_margin)),
    )

    # Plot styling: confidence-only is the only sweep that actually traces a
    # readable curve. The five formal selectors typically pile up at one
    # operating point, so we draw each with a distinct marker shape (no jitter
    # so the reader can still read off the exact x/y) and place the legend so
    # it doesn't sit on top of them.
    eps_target = float(cfg.get("calibration", {}).get("epsilon", 0.15))
    # Distinct marker per formal selector. A small x-jitter is applied at draw
    # time so they don't perfectly overlap when their operating points coincide.
    style = {
        "Confidence-only":                       {"marker": "o", "ms": 5,  "lw": 1.4, "color": "tab:blue",   "jitter": 0.000},
        "Proof-existence":                       {"marker": "s", "ms": 8,  "lw": 0,   "color": "tab:orange", "jitter": -0.020},
        "Typed-coverage":                        {"marker": "^", "ms": 8,  "lw": 0,   "color": "tab:green",  "jitter": -0.010},
        "Proved-coverage":                       {"marker": "v", "ms": 8,  "lw": 0,   "color": "tab:red",    "jitter":  0.000},
        "Margin":                                {"marker": "D", "ms": 7,  "lw": 0,   "color": "tab:purple", "jitter": +0.010},
        "CovCal (C_typ, M fixed; sweep C_prf)":  {"marker": "*", "ms": 14, "lw": 0,   "color": "black",      "jitter": +0.020},
    }

    fig, ax = plt.subplots(figsize=(6.2, 4.0))

    # Determine y-axis limit from data (with a small headroom). All operating
    # points typically sit well below 0.20; clipping the y axis is the single
    # biggest readability win over the previous version.
    all_ys: list[float] = []
    for _name, rows in sweeps.items():
        all_ys.extend(ub for _, _, _, _, ub in rows)
    y_top = max(0.20, min(1.02, max(all_ys) * 1.20 if all_ys else 0.20))

    # Cliff target band (eps).
    ax.axhspan(0.0, eps_target, color="tab:gray", alpha=0.08, zorder=0)
    ax.axhline(eps_target, color="tab:gray", lw=0.8, ls="--", zorder=1,
               label=f"$\\epsilon = {eps_target:g}$")

    for name, rows in sweeps.items():
        s = style.get(name, {"marker": "o", "ms": 6, "lw": 1.2, "color": None, "jitter": 0.0})
        jitter = s.get("jitter", 0.0)
        xs = [(m / n if n > 0 else 0.0) + jitter for _, m, _, n, _ in rows]
        ys = [ub for _, _, _, _, ub in rows]
        ax.plot(xs, ys, marker=s["marker"], ms=s["ms"], lw=s["lw"],
                color=s["color"], label=name, alpha=0.9, zorder=3)

    # Annotation pointing at the formal-selector cluster (placed below the
    # cluster so it doesn't collide with the upper-left legend).
    pe_rows = sweeps.get("Proof-existence", [])
    if pe_rows:
        _tau, m, _k, n, ub = pe_rows[0]
        x0 = m / n if n > 0 else 0.0
        ax.annotate(
            f"formal selectors overlap\n@ ({x0:.2f}, {ub:.3f})",
            xy=(x0, ub),
            xytext=(x0 + 0.10, max(0.005, ub - y_top * 0.20)),
            fontsize=8,
            ha="left",
            arrowprops=dict(arrowstyle="->", lw=0.6, color="black"),
        )

    ax.set_xlabel("Accepted fraction")
    ax.set_ylabel("Selective risk upper bound (95\\% CP)")
    ax.set_title("Selective risk vs accepted fraction (test split)")
    ax.set_xlim(0.0, 1.02)
    ax.set_ylim(0.0, y_top)
    ax.legend(loc="upper left", fontsize=7, framealpha=0.9, handlelength=2.0)
    ax.grid(True, linestyle=":", alpha=0.4)
    fig.tight_layout()

    out_dir = args.run_dir / "figures"
    out_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_dir / "selective_risk_vs_accepted.png", dpi=160)
    fig.savefig(out_dir / "selective_risk_vs_accepted.pdf")
    # Persist the raw sweep data too — useful for paper-time tweaks.
    (out_dir / "selective_risk_sweeps.json").write_text(
        json.dumps(
            {
                name: [{"tau": tau, "m": m, "k": k, "n": n, "risk_ub_95": ub}
                       for tau, m, k, n, ub in rows]
                for name, rows in sweeps.items()
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"wrote {out_dir}/selective_risk_vs_accepted.{{png,pdf}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
